/**
 * CommonJS wrapper for seoMaster.ts
 * 
 * This file automatically exports the TypeScript seoMaster module in CommonJS format.
 * It ensures compatibility with both ESM and CommonJS environments.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY - Edit seoMaster.ts instead.
 */

import * as seoMasterModule from './seoMaster';

// Re-export everything from the main module
module.exports = {
  ...seoMasterModule,
  default: seoMasterModule.default,
  defaultMeta: seoMasterModule.defaultMeta,
  routeMeta: seoMasterModule.routeMeta,
  useCaseDefinitions: seoMasterModule.useCaseDefinitions,
  getMetaForRoute: seoMasterModule.getMetaForRoute,
  getUrlPath: seoMasterModule.getUrlPath,
  generateMetaTags: seoMasterModule.generateMetaTags,
  generateFallbackContent: seoMasterModule.generateFallbackContent,
  getAllSeoInfo: seoMasterModule.getAllSeoInfo
};