/**
 * CommonJS wrapper for seoMaster.ts
 * 
 * This file automatically exports the TypeScript seoMaster module in CommonJS format.
 * It ensures compatibility with both ESM and CommonJS environments.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY - Edit seoMaster.ts instead.
 */
import * as seoMasterModule from './seoMaster';

// Create an object with all exports
const seoMasterExports = {
  ...seoMasterModule,
  default: seoMasterModule.default,
  defaultMeta: seoMasterModule.defaultMeta,
  routeMeta: seoMasterModule.routeMeta,
  useCaseDefinitions: seoMasterModule.useCaseDefinitions,
  getMetaForRoute: seoMasterModule.getMetaForRoute,
  getUrlPath: seoMasterModule.getUrlPath,
  generateMetaTags: seoMasterModule.generateMetaTags,
  generateFallbackContent: seoMasterModule.generateFallbackContent,
  getAllSeoInfo: seoMasterModule.getAllSeoInfo
};

// Support both ESM and CommonJS
export default seoMasterExports;
export const defaultMeta = seoMasterModule.defaultMeta;
export const routeMeta = seoMasterModule.routeMeta;
export const useCaseDefinitions = seoMasterModule.useCaseDefinitions;
export const getMetaForRoute = seoMasterModule.getMetaForRoute;
export const getUrlPath = seoMasterModule.getUrlPath;
export const generateMetaTags = seoMasterModule.generateMetaTags;
export const generateFallbackContent = seoMasterModule.generateFallbackContent;
export const getAllSeoInfo = seoMasterModule.getAllSeoInfo;

// For CommonJS compatibility
if (typeof module !== 'undefined' && module.exports) {
  module.exports = seoMasterExports;
}